'use strict'

const DefaultACLData = {
  ROLES: [
    { name: 'Administrator' },
    { name: 'Senior Staff' },
    { name: 'Manager' },
    { name: 'Coach' },
    { name: 'Parent' },
  ],
  PERMISSIONS: [
    { name: 'Create Users' },
    { name: 'View Users' },
    { name: 'Edit Users' },
    { name: 'Delete Users' },
    { name: 'Create Roles' },
    { name: 'Edit Roles' },
    { name: 'Delete Roles' },
    { name: 'Create Permissions' },
    { name: 'Edit Permissions' },
    { name: 'Delete Permissions' },
    { name: 'Manage User Roles' },
    { name: 'Manage Role Permissions' },
    { name: 'Create Teams' },
    { name: 'View Teams' },
    { name: 'Edit Teams' },
    { name: 'Delete Teams' },
    { name: 'Create Players' },
    { name: 'View Players' },
    { name: 'Edit Players' },
    { name: 'Delete Players' },
    { name: 'Create Standing Orders' },
    { name: 'View Standing Orders' },
    { name: 'Edit Standing Orders' },
    { name: 'Delete Standing Orders' },
  ],
  AGE_GROUPS: [
    { short_name: 'U7', name: 'Under 7' },
    { short_name: 'U8', name: 'Under 8' },
    { short_name: 'U9', name: 'Under 9' },
    { short_name: 'U10', name: 'Under 10' },
    { short_name: 'U11', name: 'Under 11' },
    { short_name: 'U12', name: 'Under 12' },
    { short_name: 'U13', name: 'Under 13' },
    { short_name: 'U14', name: 'Under 14' },
    { short_name: 'U15', name: 'Under 15' },
    { short_name: 'U16', name: 'Under 16' },
    { short_name: 'U17', name: 'Under 17' },
  ],
  TEAMS: [
    { age_group_id: 1, name: 'Under 7s' },
    { age_group_id: 2, name: 'Under 8s (Orange)' },
    { age_group_id: 2, name: 'Under 8s (Blue)' },
    { age_group_id: 3, name: 'Athletic' },
    { age_group_id: 3, name: 'United' },
    { age_group_id: 4, name: 'Pumas' },
    { age_group_id: 5, name: 'Honey Badgers' },
    { age_group_id: 6, name: 'Under 12s' },
    { age_group_id: 7, name: 'Warriors' },
    { age_group_id: 7, name: 'Gladiators' },
    { age_group_id: 8, name: 'Hawks' },
    { age_group_id: 8, name: 'Eagles' },
    { age_group_id: 9, name: 'Under 15s' },
    { age_group_id: 9, name: 'United' },
    { age_group_id: 10, name: 'Under 16s' },
    { age_group_id: 11, name: 'Under 17s' },
  ],
  PLAYERS: [
    {
      team_id: 6,
      first_name: 'Owen',
      last_names: 'Potter',
      gender: 'male',
      date_of_birth: '2010-07-27',
      status: 'full',
    },
    {
      team_id: 1,
      first_name: 'Jake',
      last_names: 'Potter',
      gender: 'male',
      date_of_birth: '2013-03-16',
      status: 'full',
    },
  ],
}

module.exports = DefaultACLData
